### ISSUE TITLE
Generate Leidos-specific files

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/arborist#11]
We need a script to generate `epitope-mappings.tsv`. It needs the columns from https://gitlab.lji.org/iedb/external/integration/-/blob/master/generate/oracle/epitope_mapped.ctl, which I'll list here in lowercase:

epitope_id, epitope_seq, epitope_start, epitope_end, source_accession, parent_accession, parent_seq, parent_start, parent_end, identity_alignment, similarity_alignment, gaps_source_alignment, gaps_parent_alignment, all_gaps, source_alignment, parent_alignment, parent_alignment_modified

I believe that these columns are just copied from the "epitope" table: epitope_id, epitope_seq, epitope_start, epitope_end, source_accession. The parent_accession is from the source-parent match. I think that parent_seq, source_alignment, parent_alignment, parent_alignment_modified will all just be the epitope_seq. The identity_alignment, similarity_alignment should always be "1.0". The  gaps_source_alignment, gaps_parent_alignment, all_gaps should always be "0.0".

**Comment by jamesaoverton** [comment]
Let's sort this file by epitope_id (numerically), so the new entries should always be at the end.

**Comment by jamesaoverton** [comment]
In the old epitope-mappings.tsv, the parent_accession is never empty. It would be good to figure out why.

**Comment by jamesaoverton** [comment]
Jason asked us to use the empty string instead of 'nan' in the "epitope_start" and "epitope_end" columns.

The table you send it working, but the code hasn't been committed yet.

**Comment by dmx2** [comment]
Need to add code for `source-parents.tsv` and `parent-proteins.tsv`

**Comment by dmx2** [comment]
Closed with #24
