### ISSUE TITLE
Add genes nodes to protein tree

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/arborist#19]
We have code for this already in `build.py`, adding to the "protein_tree_new" table. We aren't using it yet for the molecule tree, though. This issue is about finishing that and showing it to Randi.

**Comment by dmx2** [comment]
Gene nodes are now implemented as an option in `src/protein/protein_tree/build.py` and OWL can be generated by exporting protein_tree_new instead of old here:

```
build/arborist/protein-tree.ttl: build/arborist/protein-tree.built | build/arborist/nanobot.db
	rm -f $@
	ldtab export $| $@ --table protein_tree_old
```
