### ISSUE TITLE
protein tree testing: issue with expand/collapse of 'homo sapiens' node

### ISSUE THREAD

**Issue by jgbaum** [IEDB/arborist#42]
Expanding the homo sapiens node takes quite a while, presumably due to the huge number of children.  It's not a big deal since the user gets feedback through the spinner.  However, once it is open it seems it's impossible to close.  Clicking on the '-' changes the symbol to a '+', but all of the children are still displayed.

![image](https://github.com/user-attachments/assets/90646f77-4340-4bf8-8b41-007a53c72752)

**Comment by jgbaum** [comment]
Actually, it seems impossible to remove those nodes at all, no matter how many nodes are closed:

![image](https://github.com/user-attachments/assets/8c82bd58-dc4a-4184-890b-2dada5387cb0)

**Comment by jamesaoverton** [comment]
@ninablazeska This is an IEDB.org frontend issue for Leidos. Could you please move this issue.

**Comment by ninablazeska** [comment]
Issue was created in GitLab Database Maintenance board, hence closing. 
https://gitlab.lji.org/iedb/external/development/database-maintenance/-/issues/50
