### ISSUE TITLE
Protein tree selection

### ISSUE THREAD

**Issue by Marcus-Mendes** [IEDB/arborist#43]
I am reporting two bugs:

First, I recorded a video of the bug. It may be related to the protein tree, but if you try to drag and move the protein tree windows, it crashes the window. 

Second, I took a print screen of the issue. You can select the category and the subcategories. Should it be like that? Because if you choose a category, you are getting everything that is already inside it. A solution could be that if the user specifically selects a category, it automatically deselects the primary category and vice versa.

https://github.com/user-attachments/assets/e02ded3a-2c93-4441-99e6-27294c3260fe

![image](https://github.com/user-attachments/assets/4a756af3-9f64-41a5-924b-85e06c3846e4)

**Comment by jamesaoverton** [comment]
@ninablazeska This is an iedb.org website issue for Leidos. Can you tell us where bring it to their attention?

**Comment by ninablazeska** [comment]
> @ninablazeska This is an iedb.org website issue for Leidos. Can you tell us where bring it to their attention?

I've added it to the Leidos agenda for 8/22!

**Comment by ninablazeska** [comment]
I made a Gitlab ticket for issue 1 - https://gitlab.lji.org/iedb/external/development/database-maintenance/-/issues/48

Issue 2 is expected behavior and we discussed it will remain. 

Closing this ticket now!
