### ISSUE TITLE
ImmunomeBrowser  x-axis

### ISSUE THREAD

**Issue by jasonzhyan** [IEDB/arborist#44]
When I clicked the ImmunomeBrowser icon, I got 2 charts "Response Frequency" and "Epitope Assay Counts". Then I zoomed in on the chart one or more times, I noticed the x-axis of the 2 charts didn't match anymore (See snapshots). Is it supposed to be so?

<img width="1700" alt="Screenshot 2024-08-16 at 6 22 09 PM" src="https://github.com/user-attachments/assets/0e6c74a8-be9a-4c85-b094-62752a047282">

<img width="1361" alt="Screenshot 2024-08-16 at 6 12 11 PM" src="https://github.com/user-attachments/assets/9f391154-14a5-4c7a-936e-97f4c1eca995">

**Comment by jamesaoverton** [comment]
@ninablazeska This is an issue for Leidos about the frontend of the ImmunomeBrowser. (This repository is for the ontology and protein tree backend.) Can we put it on another issue tracker? Or maybe just let them know about it here? Thanks.

**Comment by ninablazeska** [comment]
> @ninablazeska This is an issue for Leidos about the frontend of the ImmunomeBrowser. (This repository is for the ontology and protein tree backend.) Can we put it on another issue tracker? Or maybe just let them know about it here? Thanks.

I've added it to the Leidos agenda for 8/22!

**Comment by ninablazeska** [comment]
I created a ticket in Gitlab - https://gitlab.lji.org/iedb/external/development/database-maintenance/-/issues/49

Closing this now.
